x = int(input('Digite um numero para ver sua tabuada: '))

print('_' * 12)
print(f'{x} x {1:2} = {x*1}')
print(f'{x} x {2:2} = {x*2}')
print(f'{x} x {3:2} = {x*3}')
print(f'{x} x {4:2} = {x*4}')
print(f'{x} x {5:2} = {x*5}')
print(f'{x} x {6:2} = {x*6}')
print(f'{x} x {7:2} = {x*7}')
print(f'{x} x {8:2} = {x*8}')
print(f'{x} x {9:2} = {x*9}')
print(f'{x} x {10:2} = {x*10}')
print('_' * 12)
